# Generated by Django 5.1.6 on 2025-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('organizador', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_visitantes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.CharField(max_length=255)),
                ('nombre_visitante', models.CharField(max_length=255)),
                ('documento_identificacion', models.CharField(max_length=50)),
                ('cat_participante', models.CharField(blank=True, max_length=255, null=True)),
                ('entrada', models.BooleanField(default=0)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.BooleanField(default=0)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
