# Generated by Django 5.1.6 on 2025-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventovisitante',
            name='cat_participante',
        ),
        migrations.AddField(
            model_name='eventocapacitacion',
            name='usuario_registro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
