# Generated by Django 5.1.6 on 2025-03-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_eventovisitante_cat_participante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventovisitante',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eventocapacitacion'),
        ),
    ]
