# Generated by Django 5.1.6 on 2025-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseacceso',
            name='estado_pase',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en uso', 'En uso'), ('dañado', 'Dañado'), ('extraviado', 'Extraviado')], max_length=50),
        ),
    ]
